version: '3.8'

# Import Supabase services
include:
  - path: ./supabase-docker/docker/docker-compose.yml

services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app # Mount local code for development
      # Add node_modules volume to prevent conflicts with host node_modules
      - /app/node_modules
      - /app/.next
    environment:
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:8000
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
    depends_on:
      - kong
    networks:
      - unfindables-net
      - supabase_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`unfindables.localhost`)"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./django:/code # Mount local code for development
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - unfindables-net
      - supabase_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.unfindables.localhost`)"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - unfindables-net
      - supabase_network

networks:
  unfindables-net:
    driver: bridge
  supabase_network:
    external: true
    name: supabase_network 