# Generated by Django 3.2.25 on 2025-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('trigger_catalog', models.CharField(max_length=255)),
                ('trigger_schema', models.CharField(max_length=255)),
                ('trigger_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_manipulation', models.CharField(max_length=32)),
                ('event_object_catalog', models.CharField(max_length=255)),
                ('event_object_schema', models.CharField(max_length=255)),
                ('event_object_table', models.CharField(max_length=255)),
                ('action_order', models.IntegerField()),
                ('action_condition', models.CharField(max_length=1024, null=True)),
                ('action_statement', models.TextField()),
                ('action_orientation', models.CharField(max_length=32)),
                ('action_timing', models.CharField(max_length=32)),
                ('action_reference_old_table', models.CharField(max_length=255, null=True)),
                ('action_reference_new_table', models.CharField(max_length=255, null=True)),
                ('action_reference_old_row', models.CharField(max_length=255, null=True)),
                ('action_reference_new_row', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'information_schema"."triggers',
                'managed': False,
            },
        ),
    ]
