# Generated by Django 5.2 on 2025-04-29 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('no_auto_run', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.GeneratedField(db_persist=True, expression=models.Case(models.When(finished_at__isnull=True, then=True), default=False, output_field=models.BooleanField()), output_field=models.BooleanField())),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_running', True)), fields=['uuid'], name='task_is_running_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_alive_at', models.DateTimeField(auto_now_add=True)),
                ('stuck', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('finished_at',), name='unique_unfinished_tide')],
            },
        ),
    ]
